In [83]:
import numpy as np

In [8]:
a = np.array([10,20,30,40,50,60])

In [10]:
print(a)

[10 20 30 40 50 60]


In [11]:
print(a[3])

40


In [13]:
# creating a 2D array 
a = np.array([[10,20,30,40,50],[1,2,3,4,5],[12,13,14,15,16]])
print(a)

[[10 20 30 40 50]
 [ 1  2  3  4  5]
 [12 13 14 15 16]]


In [17]:
# command for accessing the multiple dimenstional array is a[rows,cols]

print(a[1:2,1:5])

[[2 3 4 5]]


In [18]:
# printing only second row
print(a[1:2,0:5])

[[1 2 3 4 5]]


In [20]:
# Printing only second column
print(a[0:3,1:2])

[[20]
 [ 2]
 [13]]


In [21]:
# print only 50
print(a[0:1,4:5])

[[50]]


In [23]:
# print the shape pf array, size
print(a.shape)

(3, 5)


In [24]:
# printing the size of array
print(a.size)

15


In [29]:
# use of range function
for i in range(1,11,1):
    print(i)

1
2
3
4
5
6
7
8
9
10


In [30]:
# use of linspace function  -> 
import numpy as np

arr = np.linspace(1, 10, 5)
print(arr)


[ 1.    3.25  5.5   7.75 10.  ]


In [33]:
# use of reshape function
a = np.array([1,2,3,4,5,1,2,3,4,5])
reshaped = a.reshape(2,5)
print(reshaped)

[[1 2 3 4 5]
 [1 2 3 4 5]]


In [36]:
# use of resize function
resized = np.resize(a,(3,3))
print(resized)

[[1 2 3]
 [4 5 1]
 [2 3 4]]


In [77]:
# printing the random values between only 0 to 100
np.random.randint(0,100,(3,4))
#np.random.rand((3,4))

array([[84, 96, 41, 21],
       [35, 51, 58,  5],
       [ 1, 82, 86, 46]], dtype=int32)

In [64]:
# finding the mean, Mode, Median from the random data
data =  np.random.randint(0,100,(4,4))
data

array([[97, 31, 94, 24],
       [97, 94, 87, 45],
       [89, 78, 78, 84],
       [29, 24,  8, 89]], dtype=int32)

In [70]:
# findind the maximum of rows
arr  = np.array([[1,2,3,4,5],[9,7,6,54,3]])
max = np.max(arr,axis=1)
print(max)

[ 5 54]


In [72]:
# findind the maximum of column
arr  = np.array([[1,2,3,4,5],[9,7,6,54,3]])
max = np.max(arr,axis=0)
print(max)

[ 9  7  6 54  5]


In [82]:
# create two random matrixes and perform addition, multiplication and subtraction between these two matrix
matrix1 = np.random.randint(1,5,(4,4))
print(matrix1)
matrix2 = np.random.randint(1,5,(4,4))
print(matrix2)
add = matrix1 + matrix2
print(add)
sub  = matrix1 - matrix2
print(sub)
mul = matrix1*matrix2
print(mul)

[[3 4 2 3]
 [1 4 4 1]
 [1 3 4 3]
 [4 3 4 4]]
[[1 2 4 3]
 [4 3 3 2]
 [4 4 1 1]
 [1 3 1 3]]
[[4 6 6 6]
 [5 7 7 3]
 [5 7 5 4]
 [5 6 5 7]]
[[ 2  2 -2  0]
 [-3  1  1 -1]
 [-3 -1  3  2]
 [ 3  0  3  1]]
[[ 3  8  8  9]
 [ 4 12 12  2]
 [ 4 12  4  3]
 [ 4  9  4 12]]
