In [3]:
# Code for calculating the execution time for python_list and python array
import numpy as np
import time

In [5]:
size = 1_000_000
py_list = list(range(size))
start = time.time()
sq_list = [x**2 for x in py_list]
end = time.time()
print(f"python list is taking {end-start} time during its execution process")

# This is the code for numpy array
np_arr = np.array(py_list)
start = time.time()
sq_array = np_arr**2
end = time.time()
print(f"The execution time for numpy array is {end-start}")  

python list is taking 0.15536928176879883 time during its execution process
The execution time for numpy array is 0.0052525997161865234


In [15]:
import sys
print(f"python list is occuping {sys.getsizeof(py_list) * len(py_list)} bytes")
print(f"numpy list is occuping {sys.getsizeof(np_arr) * len(np_arr)} bytes")

python list is occuping 8000056000000 bytes
numpy list is occuping 8000112000000 bytes


In [19]:
# creating numpy array using list
import numpy as np
arr = np.array([1,2,3,4,5,6])
print(arr,type(arr))

# Printing 2D array

arr2D = np.array([[1,2,3,4,5],[6,5,4,3,2],[0,9,8,7,6]])
print(arr2D,type(arr2D))

[1 2 3 4 5 6] <class 'numpy.ndarray'>
[[1 2 3 4 5]
 [6 5 4 3 2]
 [0 9 8 7 6]] <class 'numpy.ndarray'>


In [32]:
# Different type of functions in numpy arrar
# create an array of all elements are prefilled with only 0
import numpy as np
arr1 = np.zeros((2,3),dtype="int64")
print(arr1,arr1.shape)

# create an array od size3*3 which contains whose elements are 1
arr2 = np.ones((3,3),dtype="int64")
print(arr2)

# prefilled array with particular value
arr3 = np.full((4,4),100,dtype="int64")
print(arr3)

# WAP for creating an identity matrix
arr4 = np.eye((6),dtype="int64")
print(arr4)

# WAP for range elements range(start,end,step)
arr5 = np.arange(0,11,3)
print(arr5)

# WAP for evenly spaced array
arr6 = np.linspace(1,100,3)
print(arr6)

[[0 0 0]
 [0 0 0]] (2, 3)
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]]
[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]
[0 3 6 9]
[  1.   50.5 100. ]


In [43]:
# Properties of array
import numpy as np
arr1 = np.array([[1,2,3,4,5,6,7],[1,2,3,4,5,6,7],[1,2,3,4,5,6,7]])
print(arr1.size) # it will print the total number of elements in array
print(arr1.dtype)
print(arr1.shape)  # it will print the dimensio of array
print(arr1.ndim)   # it prints the dimension of array whether it is 1D,2D,3D
float_arr1 = arr1.astype(np.float64)
print(float_arr1,float_arr1.dtype)

21
int64
(3, 7)
2
[[1. 2. 3. 4. 5. 6. 7.]
 [1. 2. 3. 4. 5. 6. 7.]
 [1. 2. 3. 4. 5. 6. 7.]] float64


In [56]:
# WAP to conversion of 2D array to 1D array
import numpy as np
arr1 = np.array([[1,2,3,4],[1,2,3,4]])
print(arr1)
print(arr1[0][0])
# reshapig the given array
reshape = arr1.reshape((4,2))
print(reshape)

# WAP to flattend the given matrix
flattened = arr1.flatten()
print(flattened)

[[1 2 3 4]
 [1 2 3 4]]
1
[[1 2]
 [3 4]
 [1 2]
 [3 4]]
[1 2 3 4 1 2 3 4]


In [58]:
# WAP for fancy indexing
import numpy as np
arr = np.array([1,2,3,4,5,6])
idx = [0,2,4]
print(arr[idx])

[1 3 5]


In [60]:
# WAP for boolean indexing
import numpy as np 
arr = np.array([1,2,3,4,5,6,7,8])
print(arr[arr > 3])

[4 5 6 7 8]


In [6]:
# slicing in arrray
# arr[start,end,step]
import numpy as np
arr1 = np.array([1,2,3,4,5,6,7,89])
print(arr1[1:4])
print(arr1[:4])


[2 3 4]
[1 2 3 4]


In [14]:
import numpy as np
nums = [1,2,3,4,5]
print(nums)
sub_arr = nums[1:4]
print(sub_arr)
sub_arr[0] = 300
print(sub_arr)
print(nums)

# for numpy array
arr = np.array([1,2,3,4,5,6])
print(arr)
sub_num_arr = arr[1:4]
print(sub_num_arr)
sub_num_arr[0] = 5000
print(sub_num_arr)
print(arr)

[1, 2, 3, 4, 5]
[2, 3, 4]
[300, 3, 4]
[1, 2, 3, 4, 5]
[1 2 3 4 5 6]
[2 3 4]
[5000    3    4]
[   1 5000    3    4    5    6]


In [15]:
# Add two complex numbers
import numpy as np
arr1 = np.array(3+6j)
arr2 = np.array(2+3j)
print(arr1+arr2)

(5+9j)


In [23]:
# WAP to print the sum of all elements of particular row and particular column in the 2D array
import numpy as np
arr = np.array([[1,2,3,4],[1,2,3,4],[1,2,3,4]])
print(arr)
print(np.sum(arr))  # printing the sum of all elements of array
print(np.sum(arr,axis=0))  # printing the sum of all elements in column wise
print(np.sum(arr,axis=1))  # printing the sum of all elements in row wise
# printing particular element form multidimensional array
print(arr[0:2,1:2])  # be remember that when you are applyong operation over array then use square bracket

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
30
[ 3  6  9 12]
[10 10 10]
[[2]
 [2]]


In [7]:
# WAP for 3D array
import numpy as np
arr = np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]],[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])
print(arr)
print(arr[1,1,1])  # (matrix number, rowNumber,ColNumber)
# print the first layer from both the matrix
print(arr[:,0,:]) # : ==> This symbol is used for extracting complete data
# Print the first complete column in both the matrix
print(arr[:,:,0])
# Replace all first element of both the matrix by value 100
arr[:,0,:] = 100
print(arr)

[[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]

 [[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]]
2
[[1 2 3 4]
 [1 2 3 4]]
[[1 1 1]
 [1 1 1]]
[[[100 100 100 100]
  [  1   2   3   4]
  [  1   2   3   4]]

 [[100 100 100 100]
  [  1   2   3   4]
  [  1   2   3   4]]]


In [16]:
# Vectorization
import numpy as np

arr = np.array([1,2,3,4,5])
arr2 = np.array([9,8,7,6,5])
print(arr**2)
print(arr+arr2)
# Broadcasting
print(arr2+5)

[ 1  4  9 16 25]
[10 10 10 10 10]
[14 13 12 11 10]


In [22]:
# Applying mathematical formulas
import numpy as np
arr = np.array([[1,2,3,4],[1,2,3,4]])
mean = arr.mean()
print(mean)
standard_deviation = arr.std()
print(standard_deviation)
# Printing the Normalize form of given matrix
normalize_arr = (arr-mean)/standard_deviation
print(normalize_arr)

2.5
1.118033988749895
[[-1.34164079 -0.4472136   0.4472136   1.34164079]
 [-1.34164079 -0.4472136   0.4472136   1.34164079]]
