### Numpy Tricks

In [8]:
import numpy as np
a = np.random.random(12)*100
b = np.random.random(12).reshape(4,3)

In [9]:
a

array([ 2.38052996, 64.48777833, 86.28683462, 15.75087458, 30.75614077,
       10.21345508, 29.38431688, 51.41898753, 14.78010519, 78.63036719,
       13.7211538 , 57.50892632])

In [10]:
b = b*100

In [11]:
b

array([[89.06435283, 17.66567107, 89.23946469],
       [60.28725495,  3.72255761, 13.59935231],
       [21.11242798, 68.35727981, 87.69745081],
       [18.91345047, 78.84846441, 94.70429561]])

In [12]:
np.sort(b)

array([[17.66567107, 89.06435283, 89.23946469],
       [ 3.72255761, 13.59935231, 60.28725495],
       [21.11242798, 68.35727981, 87.69745081],
       [18.91345047, 78.84846441, 94.70429561]])

In [13]:
np.sort(a)

array([ 2.38052996, 10.21345508, 13.7211538 , 14.78010519, 15.75087458,
       29.38431688, 30.75614077, 51.41898753, 57.50892632, 64.48777833,
       78.63036719, 86.28683462])

In [15]:
# sorting decending order
np.sort(a)[::-1]

array([86.28683462, 78.63036719, 64.48777833, 57.50892632, 51.41898753,
       30.75614077, 29.38431688, 15.75087458, 14.78010519, 13.7211538 ,
       10.21345508,  2.38052996])

In [16]:
np.where(a>50)  # return index where condition is satisfied

(array([ 1,  2,  7,  9, 11]),)

In [20]:
np.where(b>5,0,b)

array([[0.        , 0.        , 0.        ],
       [0.        , 3.72255761, 0.        ],
       [0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        ]])

In [30]:
np.argmax(b,axis=0)

array([0, 3, 3])

In [29]:
b

array([[89.06435283, 17.66567107, 89.23946469],
       [60.28725495,  3.72255761, 13.59935231],
       [21.11242798, 68.35727981, 87.69745081],
       [18.91345047, 78.84846441, 94.70429561]])

In [ ]:
-> continue after 34 minutes