### Numpy Tricks

In [1]:
import numpy as np
a = np.random.random(12)*100
b = np.random.random(12).reshape(4,3)

In [2]:
a

array([32.90737029, 81.0926504 , 57.07918238, 63.92511221,  2.33990968,
       61.30551442, 15.34475776, 76.82383603,  8.97133275, 73.95870073,
       71.09357336,  4.82335092])

In [3]:
b = b*100

In [4]:
b

array([[ 6.01717838, 66.1383437 ,  9.5387545 ],
       [35.75724814, 46.41878773, 93.16285029],
       [ 2.77864304,  0.67282085, 78.14998679],
       [82.74482044, 53.29733177, 84.93713052]])

In [5]:
np.sort(b)

array([[ 6.01717838,  9.5387545 , 66.1383437 ],
       [35.75724814, 46.41878773, 93.16285029],
       [ 0.67282085,  2.77864304, 78.14998679],
       [53.29733177, 82.74482044, 84.93713052]])

In [6]:
np.sort(a)

array([ 2.33990968,  4.82335092,  8.97133275, 15.34475776, 32.90737029,
       57.07918238, 61.30551442, 63.92511221, 71.09357336, 73.95870073,
       76.82383603, 81.0926504 ])

In [7]:
# sorting decending order
np.sort(a)[::-1]

array([81.0926504 , 76.82383603, 73.95870073, 71.09357336, 63.92511221,
       61.30551442, 57.07918238, 32.90737029, 15.34475776,  8.97133275,
        4.82335092,  2.33990968])

In [8]:
np.where(a>50)  # return index where condition is satisfied

(array([ 1,  2,  3,  5,  7,  9, 10]),)

In [9]:
np.where(b>5,0,b)

array([[0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        ],
       [2.77864304, 0.67282085, 0.        ],
       [0.        , 0.        , 0.        ]])

In [10]:
np.argmax(b,axis=0)

array([3, 0, 1])

In [11]:
b

array([[ 6.01717838, 66.1383437 ,  9.5387545 ],
       [35.75724814, 46.41878773, 93.16285029],
       [ 2.77864304,  0.67282085, 78.14998679],
       [82.74482044, 53.29733177, 84.93713052]])

In [12]:
# np.cumsum()
a = np.arange(12,24).reshape(3,4)


In [13]:
a

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [16]:
import numpy as np
np.cumsum(a,axis=0)

array([[12, 13, 14, 15],
       [28, 30, 32, 34],
       [48, 51, 54, 57]])

In [17]:
np.cumprod(a,axis=0)

array([[  12,   13,   14,   15],
       [ 192,  221,  252,  285],
       [3840, 4641, 5544, 6555]])

In [18]:
np.cumprod(a,axis=1)

array([[    12,    156,   2184,  32760],
       [    16,    272,   4896,  93024],
       [    20,    420,   9240, 212520]])

In [25]:
# np.percentile()
np.percentile(a,50)

np.float64(17.5)

In [22]:
a

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [26]:
np.histogram(a)

(array([2, 1, 1, 1, 1, 1, 1, 1, 1, 2]),
 array([12. , 13.1, 14.2, 15.3, 16.4, 17.5, 18.6, 19.7, 20.8, 21.9, 23. ]))

In [27]:
a

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [29]:
np.corrcoef(a)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])