# Numpy

In [1]:
import numpy as np
s = np.array([1,2,3,4])
print(s)

[1 2 3 4]


In [2]:
# 3D array
np.array([[[1,2,3],[1,2,3],[1,2,3]]])

array([[[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]])

In [3]:
# Float array
np.array([1,2,3,4],dtype=float)

array([1., 2., 3., 4.])

In [4]:
# np.arange -> It is used for creating a list
np.arange(1,10,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [5]:
# with reshape -> Reshaping the given list
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [6]:
# np.ones and np.zeros
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [17]:
p = np.random.random((3,4))

In [18]:
p

array([[0.30277631, 0.80515886, 0.61007134, 0.91644791],
       [0.19796929, 0.59655132, 0.97209977, 0.29379915],
       [0.27902363, 0.81217239, 0.73527819, 0.8769769 ]])

In [19]:
# np.random
a = np.random.randint(1,100,(3,4))

In [20]:
a

array([[78, 26,  6, 92],
       [27, 60, 39, 40],
       [67, 65, 25, 93]], dtype=int32)

In [21]:
# np.linspace -> linearspace
p = np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [45]:
type(p)

int

In [22]:
# np.identity
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Array Attribute

In [23]:
a1 = np.arange(10)

In [24]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
a2 = np.arange(12,dtype=float).reshape(3,4)

In [39]:
a2.itemsize

8

In [27]:
a3 = np.arange(8).reshape(2,2,2)

In [46]:
type(a3)

numpy.ndarray

In [47]:
a3.itemsize

8

In [48]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [49]:
a1,a2,a3

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]]),
 array([[[0, 1],
         [2, 3]],
 
        [[4, 5],
         [6, 7]]]))

In [50]:
a1.ndim

1

In [51]:
a2.ndim

2

In [52]:
a3.ndim

3

In [53]:
# shape
a1.shape

(10,)

In [54]:
a3.shape

(2, 2, 2)

In [55]:
# size
a1.size

10

In [56]:
a2.size


12

In [57]:
a3.size

8

In [58]:
# itemsize ->It returns the bytes taken to store the data
a1.itemsize

8

In [59]:
p = 10
print(p.itemsize)

AttributeError: 'int' object has no attribute 'itemsize'

In [60]:
a2.itemsize

8

In [61]:
# dtype
a1.dtype

dtype('int64')

### Changing datatype

In [41]:
# astype
a1.dtype

dtype('int64')

In [62]:
a1.astype((np.int32))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

### Array Operation

In [63]:
a1 = np.arange(12).reshape(4,3)
a2 = np.arange(12,24).reshape(3,4)

In [64]:
a1,a2

(array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]))

In [65]:
# scaler operation
a1*12

array([[  0,  12,  24],
       [ 36,  48,  60],
       [ 72,  84,  96],
       [108, 120, 132]])

In [66]:
a1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [67]:
# relation operator
a2>5  # It is cheking this condition to all elements

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [68]:
a2>10

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [69]:
a2>15

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [70]:
# vector operations
a1 = a1.reshape(3,4)

In [71]:
a2 = a2.reshape(3,4)

In [72]:
a1+a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [73]:
a1,a2

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]))

In [74]:
# np.round -> It is used for rouding all the value of array
a1 = np.array((2,3,0.5))

In [75]:
a1

array([2. , 3. , 0.5])

In [76]:
np.round(a1,2) 

array([2. , 3. , 0.5])

In [77]:
np.round(a1,0)

array([2., 3., 0.])

In [78]:
import numpy as np
a1 = np.random.random((3,3))
a1 = np.round(a1*100)

In [79]:
a1

array([[31.,  6., 70.],
       [73., 47., 85.],
       [37., 53., 91.]])

In [80]:
# max
np.max(a1)

np.float64(91.0)

In [81]:
# min
np.min(a1)

np.float64(6.0)

In [82]:
#prod
np.prod(a1)

np.float64(677594097152700.0)

In [83]:
# Note = axis=0 means apply operation column wise
np.max(a1,axis=0)

array([73., 53., 91.])

In [84]:
# mean
np.mean(a1)

np.float64(54.77777777777778)

In [85]:
# mode
np.median(a1)

np.float64(53.0)

In [86]:
# std
np.std(a1)

np.float64(26.063076384365758)

In [87]:
# variance
np.var(a1)

np.float64(679.2839506172841)

In [88]:
# trignometric function
np.sin(a1)

array([[-0.40403765, -0.2794155 ,  0.77389068],
       [-0.67677196,  0.12357312, -0.17607562],
       [-0.64353813,  0.39592515,  0.10598751]])

In [89]:
# dot product of two matrix
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(4,3)
np.dot(a1,a2)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [90]:
# log
np.log(a1)

C:\Users\dspri\AppData\Local\Temp\ipykernel_2848\2257561294.py:2: RuntimeWarning: divide by zero encountered in log
  np.log(a1)


array([[      -inf, 0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947, 1.94591015],
       [2.07944154, 2.19722458, 2.30258509, 2.39789527]])

In [91]:
# exponent
np.exp(a1)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

In [92]:
# round -> It is used for round of the value to the nearest integer
a1 = np.random.random((2,4))

In [93]:
a1

array([[0.3285962 , 0.165345  , 0.46468223, 0.30748138],
       [0.42223084, 0.75748401, 0.02185183, 0.39883061]])

In [94]:
 a1= a1*100

In [95]:
a1

array([[32.85962011, 16.53450004, 46.4682229 , 30.74813787],
       [42.22308386, 75.74840097,  2.18518328, 39.88306052]])

In [96]:
a1 = np.round(a1)

In [97]:
a1

array([[33., 17., 46., 31.],
       [42., 76.,  2., 40.]])

In [98]:
# floor -> Round of the lowest integral value 
a1 = np.random.random((2,3))

In [99]:
a1

array([[0.55728222, 0.62326432, 0.32839355],
       [0.91116535, 0.51211003, 0.90857753]])

In [100]:
a1 = a1*100

In [101]:
a1

array([[55.72822224, 62.32643164, 32.83935457],
       [91.1165349 , 51.21100279, 90.8577531 ]])

In [102]:
np.floor(a1)

array([[55., 62., 32.],
       [91., 51., 90.]])

In [103]:
np.ceil(a1)

array([[56., 63., 33.],
       [92., 52., 91.]])

### Indexing ans slicing

In [104]:
a1 = np.arange(10)

In [105]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [106]:
a2 = np.arange(12).reshape(3,4)

In [107]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [108]:
a3 = np.arange(8).reshape(2,2,2)

In [109]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [110]:
a1[4]

np.int64(4)

In [111]:
a2[2][2]

np.int64(10)

In [112]:
# Indexing
a2[2,2]

np.int64(10)

In [113]:
# find the value of 5 in the a3
a3[1,0,1]  #[matrix_number,row,column]

np.int64(5)

### Slicing -> Can extract multiple items at once

In [114]:
import numpy as np
a1 = np.arange(12)
a2 = np.arange(12,24)
a3 = np.arange(8).reshape(2,2,2)

In [115]:
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [116]:
a2

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [117]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [118]:
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [119]:
# slicing in 1D array
a1[2:5]

array([2, 3, 4])

In [120]:
a2 = np.arange(12).reshape(3,4)

In [121]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [122]:
a2[1:2,1:2]

array([[5]])

In [123]:
import numpy as np

a1 = np.array([[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]])

a2 = np.array([[10, 20, 30],
               [40, 50, 60],
               [70, 80, 90]])

a2[1, 2]  # row index 1, column index 2 → gives 60

np.int64(60)

In [124]:
a1 = np.arange(18).reshape(2,3,3)  # [number_of_matrix,number_Of_Rows,No_cols]

In [125]:
a1

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [126]:
# accessing a particular ele from multidimention matrix
a1[0,1:2,1:2]

array([[4]])

### Itrating

In [127]:
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [128]:
for i in a2:
    print(i)

[10 20 30]
[40 50 60]
[70 80 90]


In [129]:
for i in a2:
    for j in a2:
        print(a2[i,j])

IndexError: index 10 is out of bounds for axis 0 with size 3

In [130]:
for i in a2:        # i = each row
    for j in i:     # j = each element in that row
        print(j)

10
20
30
40
50
60
70
80
90


### reshaping

In [32]:
# reshape -> Done

In [33]:
# Transpose ->
a3 = np.arange(12,24).reshape(3,4)

In [34]:
a3

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [37]:
np.transpose(a3)

array([[12, 16, 20],
       [13, 17, 21],
       [14, 18, 22],
       [15, 19, 23]])

In [38]:
# ravel -> Convert all dimensional array in 1D
a3.ravel()

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

### Stacking  -> Simply it means add two array either horizontally or vertically

In [50]:
# horizontal
a1 = np.arange(12).reshape(3,4)

In [51]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [52]:
a2 = np.arange(12).reshape(3,4)

In [53]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [54]:
np.hstack((a1,a2))

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [55]:
np.vstack((a1,a2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### Spliting

In [58]:
# horizontal split
np.hsplit(a1,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [59]:
np.vsplit(a1,2)

ValueError: array split does not result in an equal division